version: 0.0
os: linux
files:
  - source: /application-code/app-tier
    destination: /home/ec2-user/app-tier
  - source: /application-code/web-tier
    destination: /home/ec2-user/web-tier

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/verify_server.sh
      timeout: 300
      runas: ec2-user